version: 2.0

jobs:
  build:
    docker:
      - image: node:8.9.4
    steps:
      - run:
          name: The First step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Step to print the node version
          command: |
            npm -v
